function my_build
% script to build matconvnet-1.0-beta11

matconvnetRoot = fileparts(mfilename('fullpath'));
run(fullfile(matconvnetRoot, 'matlab', 'vl_setupnn.m') );

%% CPU
vl_compilenn('enableImreadJpeg', true)

%% GPU support + other options (replace the corresponding paths)
vl_compilenn('enableGpu', true, ...
    'cudaRoot', '/usr/local/cuda', ...
    'cudaMethod', 'nvcc', ...
    'enableCudnn', true, ...
    'cudnnRoot', '/media/data/amorsy/cuda',  ...
    'enableImreadJpeg', true, ...
    'verbose', false ); 
